spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        # Soccer Service Specific Routes (more explicit - must come first for priority)
        - id: soccer-service-players
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/players
            - Path=/api/soccer/players/**
          filters:
            - StripPrefix=2
        
        - id: soccer-service-team
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/team
            - Path=/api/soccer/team/**
          filters:
            - StripPrefix=2
        
        - id: soccer-service-stadiums
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/stadiums
            - Path=/api/soccer/stadiums/**
          filters:
            - StripPrefix=2
        
        - id: soccer-service-schedules
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/schedules
            - Path=/api/soccer/schedules/**
          filters:
            - StripPrefix=2
        
        - id: soccer-service-search
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/search
            - Path=/api/soccer/search/**
          filters:
            - StripPrefix=2
        
        # Soccer Service Routes - General Route (must come last)
        - id: soccer-service
          uri: lb://SOCCERSERVICE
          predicates:
            - Path=/api/soccer/**
          filters:
            - StripPrefix=2
        
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        
        # Culture Service Routes
        - id: culture-service
          uri: lb://culture-service
          predicates:
            - Path=/api/culture/**
          filters:
            - StripPrefix=2
        
        # Micro Service Routes
        - id: micro-service
          uri: lb://micro-service
          predicates:
            - Path=/api/micro/**
          filters:
            - StripPrefix=2
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://nextjs:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 5

